Vagrant.configure("2") do |config|
    config.vm.define "vm01" do |vm01|
        vm01.vm.box = "cloudicio/ubuntu-server"
        vm01.vm.box_version = "24.04.1"
        vm01.vm.network "private_network", ip: "192.168.56.4"
        vm01.vm.provider "virtualbox" do |vb|
            vb.name = "Ubuntu_24.04_VM01"
            vb.memory = "1024"
            vb.cpus = 1
        end
        vm01.ssh.password = "bluemejia"
        vm01.vm.provision "file", source: "../ssh/vagrant_key.pub", destination: "/home/vagrant/.ssh/authorized_keys"
        vm01.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/authorized_keys" 
    end
    config.vm.define "vm02" do |vm02|
        vm02.vm.box = "cloudicio/ubuntu-server"
        vm02.vm.box_version = "24.04.1"
        vm02.vm.network "private_network", ip: "192.168.56.5"
        vm02.vm.provider "virtualbox" do |vb|
            vb.name = "Ubuntu_24.04_VM02"
            vb.memory = "1024"
            vb.cpus = 1
        end
        vm02.ssh.password = "bluemejia"
        vm02.vm.provision "file", source: "../ssh/vagrant_key.pub", destination: "/home/vagrant/.ssh/authorized_keys"
        vm02.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/authorized_keys" 
    end
end