---
- name: Install Nginx
  hosts: all
  become: yes
  tasks:
    - name: update packages
      apt:
        update_cache: yes
    - name: Install nginx
      apt: 
        name: nginx
        state: present
    - name: Check ngnix service
      service:
        name: nginx
        state: started
        enabled: yes
